ORM_PATH = "sqlite:///data/instalker_orm.sqlite?check_same_thread=False"

INITIAL_STATE_PATH = "data/instastate.pickle"

FOLLOW_PERIOD_DAYS = 1

# Delays
DELAY_MODIFIER = 1

DEFAULT_DELAY_SECONDS = 30 * DELAY_MODIFIER
ITER_DELAY_SECONDS = 5 * 60 * DELAY_MODIFIER
API_RESET_DELAY_SECONDS = 60 * 60 * DELAY_MODIFIER
LIKE_FAILURE_DELAY_SECONDS = 5 * 60 * DELAY_MODIFIER

# Limits
MAX_FOLLOWERS_CRAWLED = 400
